name: "Test"

on:
  workflow_dispatch: {}
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Unit Test
        run: godot -s addons/gut/gut_cmdln.gd --headless
        timeout-minutes: 1
